### ISSUE TITLE
can not find pKey at all 

### ISSUE THREAD

**Issue by kuw13** [Etayson/BSGS-cuda#7]
private key : 0000000000000000000000000000000000000000000000000023dc0000000001
pkey : 0222479403f4eb300b997bc76feab5e9e0631be2d2b006e3d87ec586bd48a94720

https://ibb.co/rMFLFMv

i try many time with many keys with not working at all

**Comment by Etayson** [comment]
`Load BIN file:79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798_4194304_33554432_htCPU.BIN
[0] chunk:301989888b
START RANGE= 0000000000000000000000000000000000000000000000000000000000000001
SUBpoint= (79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798, b7c52588d95c3b9aa25b0403f1eef75702e84bb7597aabe663b82f6f04ef2777)
FINDpubkey: 0222479403f4eb300b997bc76feab5e9e0631be2d2b006e3d87ec586bd48a94720
GPU#0 Cnt:0000000000000000000000000000000000000000000000000000000000000001
***********GPU#0************
KEY[1]: 0x0000000000000000000000000000000000000000000000000023dc0000000001
   Pub: 0222479403f4eb300b997bc76feab5e9e0631be2d2b006e3d87ec586bd48a94720
****************************
Found in 1 seconds`

You can`t find key because you set wrong start range -pk
CNT in cmd it is not privatekey where now do seraching.. it is counter.
Set -pk 0x1 and you will find key.

**Comment by kuw13** [comment]
how can u add 3 gpu or more ?

**Comment by Etayson** [comment]
Use -d parameter
-d 0,1,2
Mean use GPU0, GPU1, GPU2
Please read readme.md file before using.

**Comment by kuw13** [comment]
I did but i did not configure how many -t and -b as block and how many -w with -htsz

**Comment by Etayson** [comment]
-t select 256 or 512
-b dependency of SM count of your card (Also you can see in cmd number of compute units it is the same)
-p select 256 for example
in your screen i see that your GPU have 1689 MB free memory so select -w 27
because using -w 27 select -htsz 26

**Comment by kuw13** [comment]
Thanks
